services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
